version: '2'

services:
  client:
    container_name: lev_client_container
    restart: always
    image: nginx
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - backend

  backend:
    container_name: lev_server_container
    restart: always
    image: flask
    build: ./backend
    volumes:
      - ./db-data:/data/www/data